version: "3.9"

services:
  auth-service:
    build: ./services/auth
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@auth-db:5432/authdb
    depends_on:
      - auth-db

  user-service:
    build: ./services/user
    ports:
      - "8002:8002"

  auth-db:
    image: postgres:15
    container_name: auth-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
